version: '3.8'

services:
  backend:
    build: ./backend
    container_name: beyondmaps-backend
    ports:
      - "5000:5000"
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - NODE_ENV=production
